-
  name: 'Carbon.OutOfBandRendering - RenderingController->show'
  uriPattern: 'carbon/outofbandrendering'
  defaults:
    '@package':    'Carbon.OutOfBandRendering'
    '@controller': 'Rendering'
    '@action':     'show'
    '@format':     'html'
  appendExceedingArguments: TRUE
  httpMethods: ['GET']
