-
  name: 'Ttree.OutOfBandRendering - RenderingController->show'
  uriPattern: 'ttree/outofbandrendering'
  defaults:
    '@package':    'Ttree.OutOfBandRendering'
    '@controller': 'Rendering'
    '@action':     'show'
    '@format':     'html'
  appendExceedingArguments: TRUE
  httpMethods: ['GET']
