Ttree:
  OutOfBandRendering:
    presets: [ ]
#    presets:
#      'sample':
#        typoScriptPath: 'page<Neos.NodeTypes:Page>/body<TYPO3.TypoScript:Template>/content/main<TYPO3.Neos:PrimaryContent>/collection<TYPO3.TypoScript:Matcher>/element<Your.Package:Collection>'
