Carbon:
  OutOfBandRendering:
    presets: [ ]
#    presets:
#      'sample':
#        typoScriptPath: 'page<Neos.NodeTypes:Page>/body<Neos.Fusion:Template>/content/main<Neos.Neos:PrimaryContent>/collection<Neos.Fusion:Matcher>/element<Your.Package:Collection>'
